"""What to do about a finding, from authoritative sources where they exist.

Two kinds of finding need two kinds of answer.

A finding carrying a CVE - every rule generated by rulegen.py does - has an
authoritative answer already written down. CISA's Known Exploited
Vulnerabilities catalogue publishes `cisaRequiredAction`, the mandated
remediation text, with a due date; NVD carries vendor references tagged Patch or
Vendor Advisory. Neither needs to be invented or searched for.

A malware finding has no CVE and no vendor patch. What it has is a response
shape that depends on what was found: a web shell means credentials are
suspect and web logs need reading; ransomware means isolate before anything
else. Those are playbooks, and they are written here rather than fetched,
because they do not change per incident.

Nothing here is generated text presented as advice. Where the answer is known it
is quoted from its source with attribution; where it is not, the playbook says
what class of response applies and leaves the judgement to the analyst.
"""
from __future__ import annotations

import json
import re
import threading
from pathlib import Path

from .store import now_iso

CVE_RE = re.compile(r"CVE-\d{4}-\d{4,7}", re.IGNORECASE)
PATCH_TAGS = {"Patch", "Vendor Advisory", "Mitigation", "Release Notes"}
GUIDANCE_SCHEMA = 2

# Keyed by rule namespace first, then by tag. Ordered - step one is step one.
PLAYBOOKS = {
    "webshell": {
        "summary": "A server-side backdoor gives an attacker command execution "
                   "as the web server user. Assume the host is compromised.",
        "steps": [
            "Preserve the file and its timestamps before removing anything.",
            "Read the web server access log for requests to this path - the "
            "source addresses are the operator, and the response sizes show "
            "what was taken.",
            "Rotate every credential the web server can reach: database, API "
            "keys, cloud roles, connection strings in config files.",
            "Look for siblings. A web shell is rarely alone; scan the whole "
            "document root, not just the upload directory.",
            "Find the upload path that allowed it and fix the validation.",
        ],
    },
    "ransomware": {
        "summary": "Encryption tooling or an extortion artifact. Time matters "
                   "more than analysis here.",
        "steps": [
            "Isolate the host from the network before investigating further.",
            "Do not reboot - keys occasionally survive in memory.",
            "Check whether volume shadow copies still exist and protect them.",
            "Identify the scope of encrypted files before restoring anything.",
            "Preserve the ransom note and any wallet addresses as evidence.",
        ],
    },
    "credential_theft": {
        "summary": "Tooling aimed at stored or in-memory credentials. Treat "
                   "every credential reachable from this host as exposed.",
        "steps": [
            "Rotate credentials for every account used on this host, "
            "prioritising domain and service accounts.",
            "Invalidate active sessions and refresh tokens.",
            "Review authentication logs for use of those credentials elsewhere.",
            "Check for persistence - credential theft is rarely the first step.",
        ],
    },
    "c2_network": {
        "summary": "Command-and-control capability. The indicators extracted "
                   "from this file are the hunt.",
        "steps": [
            "Block the extracted addresses and domains at the egress point.",
            "Search proxy, firewall and DNS logs for prior contact with them.",
            "Establish first-contact time - that is the intrusion's start, not "
            "the detection time.",
            "Look for persistence mechanisms on any host that talked to them.",
        ],
    },
    "info_stealer_rat": {
        "summary": "Data theft or hands-on-keyboard remote access.",
        "steps": [
            "Assume browser-stored credentials, cookies and session tokens on "
            "this host are exfiltrated.",
            "Rotate credentials and invalidate sessions, including cloud "
            "consoles reachable from the browser profile.",
            "Check for cryptocurrency wallet files if any were present.",
        ],
    },
    "supply_chain": {
        "summary": "A package or build artifact that runs code at install time.",
        "steps": [
            "Quarantine the artifact and stop any pipeline consuming it.",
            "Identify every build that consumed this version.",
            "Rotate CI secrets - install hooks run with the pipeline's "
            "environment, including tokens.",
            "Pin the dependency to a known-good version and rebuild.",
        ],
    },
    "rmm_tunnel_abuse": {
        "summary": "Remote access or tunnelling tooling configured for "
                   "unattended use. This may be legitimate - confirm first.",
        "steps": [
            "Confirm with the owning team whether this deployment is "
            "sanctioned. Plenty of organisations run these deliberately.",
            "If unsanctioned: terminate active sessions and remove the service.",
            "Check the configured password or token - a preset unattended "
            "credential means anyone holding it has access.",
            "Review outbound connections for the tunnel's destination.",
        ],
    },
    "office_macro_malware": {
        "summary": "A document that executes on open.",
        "steps": [
            "Identify the delivery path - mail, upload, or share.",
            "Find other recipients of the same document.",
            "Check whether the macro ran: look for spawned processes and "
            "child script interpreters around the open time.",
        ],
    },
    "cryptominer": {
        "summary": "Resource abuse. Lower urgency, but it means someone had "
                   "enough access to run code.",
        "steps": [
            "Terminate the miner and remove its persistence.",
            "Treat the access path as the real finding - mining is a symptom.",
            "Check the configured pool address against outbound connections.",
        ],
    },
    "recon_persistence": {
        "summary": "Discovery activity or a persistence mechanism.",
        "steps": [
            "Enumerate and remove the persistence entry itself.",
            "Establish what else ran under it and when it was created.",
            "Persistence implies prior access - find the initial vector.",
        ],
    },
    "vulnerable_component": {
        "summary": "A known-vulnerable component is present. This is exposure, "
                   "not compromise - nothing here says it has been exploited.",
        "steps": [
            "Confirm the component is actually in use, not merely present on "
            "disk in an unused artifact.",
            "Apply the vendor patch named below, or upgrade past the affected "
            "version range.",
            "If it is a KEV entry, treat the CISA due date as the deadline.",
        ],
    },
}

PLAYBOOKS["windows_threats"] = {
    "summary": "Windows host tradecraft - encoded commands, defence evasion, "
               "or credential tooling.",
    "steps": [
        "Establish what ran and under which account.",
        "Check for persistence created around the same time.",
        "Rotate credentials used on this host if anything credential-adjacent "
        "fired.",
        "Preserve the file before deleting it - the command line is evidence.",
    ],
}
PLAYBOOKS["linux_threats"] = PLAYBOOKS["windows_threats"]
PLAYBOOKS["web_fraud_skimmer"] = PLAYBOOKS["webshell"]
PLAYBOOKS["phishing_social_engineering"] = {
    "summary": "A lure aimed at a person rather than the system.",
    "steps": [
        "Identify who received it and whether anyone interacted.",
        "Pull the same lure from other mailboxes or upload paths.",
        "If credentials may have been entered, rotate them and check for "
        "logins from unfamiliar addresses.",
    ],
}

# Checked before tags: a rule's subject beats its category. Ordered, because
# the first match wins and the specific terms must come first.
RULE_KEYWORDS = [
    ("ransom", "ransomware"),
    ("lockbit", "ransomware"),
    ("conti", "ransomware"),
    ("revil", "ransomware"),
    ("sodinokibi", "ransomware"),
    ("webshell", "webshell"),
    ("skimmer", "web_fraud_skimmer"),
    ("lsass", "credential_theft"),
    ("credential", "credential_theft"),
    ("keylog", "credential_theft"),
    ("miner", "cryptominer"),
    ("xmrig", "cryptominer"),
    ("stratum", "cryptominer"),
    ("beacon", "c2_network"),
    ("cobalt", "c2_network"),
    ("reverse_shell", "c2_network"),
    ("tunnel", "rmm_tunnel_abuse"),
    ("stealer", "info_stealer_rat"),
    ("macro", "office_macro_malware"),
    ("persistence", "recon_persistence"),
]

TAG_ALIASES = {
    "kev": "vulnerable_component",
    "phishing": "phishing_social_engineering",
    "malware": "windows_threats",
    "suspicious": "windows_threats",
}

DEFAULT_PLAYBOOK = {
    "summary": "No specific playbook for this rule category.",
    "steps": [
        "Review the matched strings to understand what fired.",
        "Check the extracted indicators for infrastructure worth hunting.",
        "If this is a false positive, mark it as such - that feeds rule tuning.",
    ],
}


class Guidance:
    """Assembles remediation guidance, caching the CVE lookups."""

    def __init__(self, cache_dir: str, nvd=None):
        self.cache_dir = Path(cache_dir)
        self.nvd = nvd
        self._lock = threading.Lock()
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ cves
    @staticmethod
    def cve_ids(finding: dict) -> list:
        """CVEs named by the rules that fired, or extracted from the file."""
        found = []
        for match in finding.get("matches", []) or []:
            value = str((match.get("meta") or {}).get("cve") or "")
            for cve in CVE_RE.findall(value):
                if cve.upper() not in found:
                    found.append(cve.upper())
        for indicator in (finding.get("iocs") or {}).get("indicators", []) or []:
            if indicator.get("type") == "cve":
                cve = str(indicator.get("value", "")).upper()
                if cve and cve not in found:
                    found.append(cve)
        return found[:8]

    def _cve_detail(self, cve_id: str) -> dict:
        cached = self.cache_dir / (cve_id + ".json")
        if cached.exists():
            try:
                detail = json.loads(cached.read_text(encoding="utf-8"))
                if detail.get("schema") == GUIDANCE_SCHEMA:
                    return detail
            except (OSError, json.JSONDecodeError):
                pass
        if self.nvd is None:
            return {"id": cve_id, "error": "no NVD client configured"}

        try:
            record = self.nvd.fetch_cve(cve_id)
        except Exception as exc:
            return {"id": cve_id, "error": str(exc)}
        if record.get("error"):
            return {"id": cve_id, "error": record.get("error")}

        detail = {
            "schema": GUIDANCE_SCHEMA,
            "id": cve_id,
            "kev": bool(record.get("kev")),
            "kev_name": record.get("kev_name", ""),
            "required_action": record.get("kev_required_action", ""),
            "action_due": record.get("kev_action_due", ""),
            "exploit_added": record.get("exploit_added", ""),
            "patch_refs": (record.get("patch_refs") or [])[:8],
            "fetched_at": now_iso(),
        }
        try:
            cached.write_text(json.dumps(detail, indent=1), encoding="utf-8")
        except OSError:
            pass
        return detail

    # -------------------------------------------------------------- playbooks
    @staticmethod
    def playbook_for(finding: dict) -> dict:
        """Namespace, then rule name, then tag, then default.

        Rule names are consulted before tags because a rule's *subject* is a
        better guide than its category: `Ransom_Note_Template` lives in the
        `windows_threats` namespace and carries the tag `malware`, neither of
        which says ransomware. Matching the name gets the right playbook.
        """
        namespaces, tags, names = [], [], []
        for match in finding.get("matches", []) or []:
            namespaces.append(str(match.get("namespace") or "").lower())
            tags.extend(str(t).lower() for t in (match.get("tags") or []))
            names.append(str(match.get("rule") or "").lower())
        names.extend(str(r).lower() for r in finding.get("rule_names", []) or [])

        # Rule name first. `windows_threats` is a catch-all holding ransom-note,
        # credential-dumping and PowerShell rules alike, so its namespace says
        # far less than the rule's own name does.
        for keyword, key in RULE_KEYWORDS:
            if any(keyword in name for name in names):
                return dict(PLAYBOOKS[key], source="rule:*" + keyword + "*")

        for key in namespaces:
            if key in PLAYBOOKS:
                return dict(PLAYBOOKS[key], source="namespace:" + key)

        for key in tags:
            if key in PLAYBOOKS:
                return dict(PLAYBOOKS[key], source="tag:" + key)
            mapped = TAG_ALIASES.get(key)
            if mapped:
                return dict(PLAYBOOKS[mapped], source="tag:" + key)

        return dict(DEFAULT_PLAYBOOK, source="default")

    # ------------------------------------------------------------------- main
    def for_finding(self, finding: dict) -> dict:
        cves = self.cve_ids(finding)
        details = [self._cve_detail(c) for c in cves]
        kev = [d for d in details if d.get("kev")]
        return {
            "finding": finding.get("id"),
            "file_name": finding.get("file_name"),
            "severity": finding.get("severity"),
            "playbook": self.playbook_for(finding),
            "cves": details,
            "kev_count": len(kev),
            "required_actions": [
                {"cve": d["id"], "action": d["required_action"],
                 "due": d.get("action_due", "")}
                for d in kev if d.get("required_action")
            ],
            "patch_refs": [r for d in details for r in d.get("patch_refs", [])][:12],
            "generated_at": now_iso(),
        }
